### ISSUE TITLE
Special handling for ALL CAPS acronyms?

### ISSUE THREAD

**Issue by tp** [ianstormtaylor/to-slug-case#1]
Right now "HTTP" becomes "h-t-t-p" and RFC becomes "r-f-c".

I would assume similar project have a list of acceptable acronyms that should be converted in a special way (I would expect "http" and "rfc" for the above result, as obvious examples).

What is your opinion on this?

**Comment by ianstormtaylor** [comment]
Agreed about those results, I think we can achieve it without special-casing, since I think it's related to this issue: https://github.com/ianstormtaylor/to-case/issues/5#issuecomment-203170150

**Comment by ianstormtaylor** [comment]
Just published `to-no-case@1.0.1` so this bug should be fixed if you reinstall.
